baseURL = 'https://blogxiaozheng.site/'
languageCode = 'zh-CN'
title = '小郑的自留地'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = '你好!'
homeIntroContent = """
这里是我记录学习心得、旅途故事与娱乐活动的小角落。我喜欢把灵感、收获和快乐都留在这里，期待和你分享交流 (ᕑᗢᓫ∗)˒
"""

# Collection to display on home
homeCollectionTitle = '时间轴'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Footer
showFooter = true
footerContent = """
**Xiaozheng** · © 2025 
Powered by [Hugo](https://gohugo.io/) and [tomfran/typo](https://github.com/tomfran/typo)
"""

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = false

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/Xiaozheng03Asada/"

[[params.social]]
name = "bilibili"
url = "https://space.bilibili.com/21958901/"


# Main menu pages
[[params.menu]]
name = "主页"
url = "/"

[[params.menu]]
name = "分类"
url = "/tags"

[[params.menu]]
name = "时间轴"
url = "/posts"

[[params.menu]]
name = "关于"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = true
repo = "Xiaozheng03Asada/Xiaozheng03Asada.github.io"
repoid = "R_kgDOQBKVLg"
category = "General"
categoryid = "DIC_kwDOQBKVLs4Cwj23"
mapping = "pathname"
theme = "preferred_color_scheme"

[params.umami]
enable = true
websiteId = "6b19b065-a8db-403e-80b0-1ff1da10ae24"
jsLocation = "https://cloud.umami.is/script.js"

